import type { SkillDefinition } from './types';

export const markXxxSkills: SkillDefinition[] = [
  {
    id: 'markxxx.browser-control',
    source: 'mark-xxx',
    title: 'Browser Control',
    category: 'automation',
    description: 'Automate browser actions and navigation flows.',
    entrypointHint: 'actions/browser_control.py',
  },
  {
    id: 'markxxx.cmd-control',
    source: 'mark-xxx',
    title: 'Command Control',
    category: 'automation',
    description: 'Run and manage shell/command-line actions.',
    entrypointHint: 'actions/cmd_control.py',
  },
  {
    id: 'markxxx.code-helper',
    source: 'mark-xxx',
    title: 'Code Helper',
    category: 'developer',
    description: 'Assist with coding tasks and code generation support.',
    entrypointHint: 'actions/code_helper.py',
  },
  {
    id: 'markxxx.computer-control',
    source: 'mark-xxx',
    title: 'Computer Control',
    category: 'system',
    description: 'General computer interaction and control routines.',
    entrypointHint: 'actions/computer_control.py',
  },
  {
    id: 'markxxx.computer-settings',
    source: 'mark-xxx',
    title: 'Computer Settings',
    category: 'system',
    description: 'Read or adjust common machine settings.',
    entrypointHint: 'actions/computer_settings.py',
  },
  {
    id: 'markxxx.desktop',
    source: 'mark-xxx',
    title: 'Desktop Operations',
    category: 'system',
    description: 'Desktop-level operations and interaction helpers.',
    entrypointHint: 'actions/desktop.py',
  },
  {
    id: 'markxxx.dev-agent',
    source: 'mark-xxx',
    title: 'Dev Agent',
    category: 'developer',
    description: 'Developer-agent style workflows and coding assistance.',
    entrypointHint: 'actions/dev_agent.py',
  },
  {
    id: 'markxxx.file-controller',
    source: 'mark-xxx',
    title: 'File Controller',
    category: 'file',
    description: 'File and folder management operations.',
    entrypointHint: 'actions/file_controller.py',
  },
  {
    id: 'markxxx.flight-finder',
    source: 'mark-xxx',
    title: 'Flight Finder',
    category: 'travel',
    description: 'Search and compare flight information.',
    entrypointHint: 'actions/flight_finder.py',
  },
  {
    id: 'markxxx.open-app',
    source: 'mark-xxx',
    title: 'Open App',
    category: 'system',
    description: 'Launch desktop applications.',
    entrypointHint: 'actions/open_app.py',
  },
  {
    id: 'markxxx.reminder',
    source: 'mark-xxx',
    title: 'Reminder',
    category: 'productivity',
    description: 'Create and manage reminders.',
    entrypointHint: 'actions/reminder.py',
  },
  {
    id: 'markxxx.screen-processor',
    source: 'mark-xxx',
    title: 'Screen Processor',
    category: 'vision',
    description: 'Process and analyze screen content.',
    entrypointHint: 'actions/screen_processor.py',
  },
  {
    id: 'markxxx.send-message',
    source: 'mark-xxx',
    title: 'Send Message',
    category: 'communication',
    description: 'Compose and send messages through integrated channels.',
    entrypointHint: 'actions/send_message.py',
  },
  {
    id: 'markxxx.weather-report',
    source: 'mark-xxx',
    title: 'Weather Report',
    category: 'utility',
    description: 'Fetch weather details and forecasts.',
    entrypointHint: 'actions/weather_report.py',
  },
  {
    id: 'markxxx.web-search',
    source: 'mark-xxx',
    title: 'Web Search',
    category: 'research',
    description: 'Run web research and result retrieval tasks.',
    entrypointHint: 'actions/web_search.py',
  },
  {
    id: 'markxxx.youtube-video',
    source: 'mark-xxx',
    title: 'YouTube Video',
    category: 'media',
    description: 'Search and interact with YouTube content workflows.',
    entrypointHint: 'actions/youtube_video.py',
  },
];
